blog/urls.py
from django.urls import path
from django.contrib import admin
from . import views
from django.conf.urls import url
#from django.contrib.auth.views import post_list

from .views import emailView, successView

urlpatterns = [
    path('', views.index, name='index'),
   # path('', views.post_list, name='post_list')
    url(r'^post_list/$', views.post_list, name='post_list'),
     path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('email/', views.emailView, name='email'),
    path('success/' , views.successView, name='success'),
]

sampleproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    
  

blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)
        
class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

blog/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from .models import Post
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from .forms import PostForm
from .forms import ContactForm
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail, BadHeaderError

# Create your views here.
def index(request):
    return render(request, 'blog/index.html', {})

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

#def post_new(request):
#    form = PostForm()
#    return render(request, 'blog/post_edit.html', {'form': form})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})



def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('success')
    return render(request, "blog/email.html", {'form': form})

def successView(request):
    return render(request, 'blog/sucess.html', {})

blog/templates/blog/base.html
{% load static %}
<html>

<head>
    <title>Risecode</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href='{% static "css/blog.css" %}'>
</head>

<body>
    <div class="page-header">
        {% if user.is_authenticated %}
        <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a> 
        {% endif %}


        <h1><a href="/"><img src="static/css/img/resized22.png"></a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %} {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

blog/templates/blog/email.html
{% load static %}
<html>

<head>
    <title>Risecode</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href='{% static "css/blog.css" %}'>
</head>

<body>

    <div class="wrappers">
        <div class="page-header">
    <h4 id="h4text"><a href="/">Home</a></h4>
    </div>
    
        <div class=conte> 
        
               <h1 id="mestext">Write a Message</h1>
<form class="emailcont" method="post">
    {% csrf_token %}
     <input name="from_email" required="" id="id_from_email" type="email" placeholder="Email adress..">
     <input name="subject" required="" id="id_subject" type="text" placeholder="Subject..">
     <textarea name="message" cols="40" rows="10" required="" id="id_message" placeholder="Message.."></textarea>
    
    <div class="form-actions">
      <button class="newbtn" type="submit">Send</button>
    </div>
</form>
        
        </div>
   
   
   
   
    </div>

    

blog/templates/blog/index.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <title>Risecode</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href='{% static "css/style.css" %}' rel="stylesheet" />

</head>

<body>



    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-main">
                   <span class="sr-only">Toggle navigation</span> 
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><img src= "static/css/img/resized22.png"></a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-main">
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="active" href="#home">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#services">Services</a></li>
                    <li><a href="{% url 'post_list'  %}">Articles</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="home">
        <div class="landing-text">
            <h1><span id="namelogo">RISING</span>CODE</h1>
            <h3>Learn the basic bulding blocks</h3>
            
            <!--/overlay contact form 
            
            <div id="overlay" >
  

<div class="containerr">
 <h3>Contact Form</h3>
  <form action="/action_page.php">
    <label for="fname"></label>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">

    <label for="lname"></label>
    <input type="text" id="lname" name="lastname" placeholder="Your Email adress..">

    <label for="subject"></label>
    <textarea id="subject" name="subject" placeholder="Write a Message.." style="height:200px"></textarea>
    
    <input type="button" value="Close" onclick="off()">
    <input type="submit" value="Submit">
    
  </form>
</div>
</div> -->
            <a href="{% url 'email'  %}" class="btn btn-defualt btn-lg" >Get Started</a>

        </div>
    </div>

    <a name="about" />
    <div class="clearfix"></div>
    <div class="padding">

        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <img src="static/css/img/bootstrap.png">
                </div>

                <div class="col-sm-6 text-center">
                    <h2>All About Risingcode.</h2>
                    <p class="lead"> non et suscipit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel error reiciendis, quia alias et quo porro expedita, laudantium eligendi adipisci perferendis non corporis aliquam dolores quis quaerat hic reprehenderit voluptas!</p>

                    <p class="lead">Lorffeem ipsum dolor sit amet, consectetur adipisicing elit. Minima, laborum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error totam, esse distinctio non et suscipit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel error reiciendis, quia alias et quo porro expedita, laudantium eligendi adipisci perferendis non corporis aliquam dolores quis quaerat hic reprehenderit voluptas!</p>
                </div>
            </div>
        </div>
    </div>

    <a name="services" />
    <div class="clearfix"></div>
    <div class="padding">

        <div class="container" id="servicesSection">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <h4>Create websites</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate accusantium magni amet nobis autem excepturi voluptates earum quas fugit dignissimos repudiandae labore mollitia alias nisi, sunt, delectus esse tempora quibusdam!</p>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <img src="static/css/img/htm.png" class="img-responsive">
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <h4>Design android app </h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate accusantium magni amet nobis autem excepturi voluptates earum quas fugit dignissimos repudiandae labore mollitia alias nisi, sunt, delectus esse tempora quibusdam!</p>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <img src="static/css/img/android.png" class="img-responsive">
                </div>
            </div>
        </div>
    </div>
    <div id="fixed">

    </div>


    <div class="padding">
        <div class="container">
            <div class="row">

                <div class="col-sm-6 ">
                    <h4>Here's the cool thing about Bootstrap...</h4>
                    <p> non et suscipit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel error reiciendis, quia alias et quo porro expedita, laudantium eligendi adipisci perferendis non corporis aliquam dolores quis quaerat hic reprehenderit voluptas!</p>

                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima, laborum Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error totam, esse distinctio non et suscipit?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vel error reiciendis, quia alias et quo porro expedita, laudantium eligendi adipisci perferendis non corporis aliquam dolores quis quaerat hic reprehenderit voluptas!</p>
                </div>

                <div class="col-sm-6">
                    <img src="static/css/img/boots.jpeg" style="border-radius: 10%;">
                </div>

            </div>
        </div>
    </div>

    <footer class="container-fluid text-center">
        <div class="clearfix"></div>
        <a name="contact" />

        <div class="row">
            <div class="col-sm-4">
                <h3>Contact Us</h3>
                <br>
                <h4>Our adress and contact info here.</h4>
            </div>
            <div class="col-sm-4">
                <h3>Connect</h3>
                <a href="https://www.facebook.com" class="fa fa-facebook"></a>
                <a href="https://www.twitter.com" class="fa fa-twitter"></a>
                <a href="https://www.youtube.com" class="fa fa-youtube"></a>
                <a href="https://www.google.com/" class="fa fa-google"></a>
                <a href="#" class="fa fa-linkedin"></a>
            </div>
            <div class="col-sm-4">
                <img src="static/css/img/resized3.png" class="icon">
            </div>
        </div>
    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <script>
        $(function() {
            $('a[href*=#]:not([href=#])').click(function() {
                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.substr(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            });
        });

      
        function on() {
    document.getElementById("overlay").style.display = "block";
}

function off() {
    document.getElementById("overlay").style.display = "none";
}

    </script>



</body>

</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %} {% block content %}

<div class="post">
    {% if post.published_date %}
    <div class="date">
        {{ post.published_date }}
    </div>
    {% endif %}
    
      {% if user.is_authenticated %}
    <a class="btn btn-default" href="{% url 'post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a> 
    {% endif %}
    
    <h1>{{ post.title }}</h1>
    <p>{{ post.text|linebreaksbr }}</p>
    
   <a  href="{% url 'post_list' %}"> <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">
  Back
</button></a>
</div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
         <a  href="{% url 'post_list' %}"> <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">
  Back
</button></a>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr|truncatechars:320 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/sucess.html
{% load static %}
<html>

<head>
    <title>Risecode</title>
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href='{% static "css/blog.css" %}'>
</head>

<body>

    <div class="wrappers">
        <div class="page-header">
    
    </div>
    
   <p>Success! Thank you for your message.</p>
   <a href="/" ><h1>Back</h1></a>